apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoservice
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: demoservice
  template:
    metadata:
      labels:
        app: demoservice
    spec:
      containers:
      - name: demoservice
        image: okteto.dev/demoservice
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: demoservice
  labels:
    app: demoservice
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      name: demoservice
  selector:
    app: demoservice
